# Generated by Django 6.0.5 on 2026-07-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_videoview'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='codec',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='video',
            name='container',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AddField(
            model_name='video',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='sha256_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='video',
            name='storage_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
