# Generated by Django 6.0.5 on 2026-07-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_codec_video_container_video_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='original_file_size',
            field=models.PositiveBigIntegerField(default=0, help_text='File size in bytes at upload time'),
        ),
        migrations.AddField(
            model_name='video',
            name='quarantine_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='scan_duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='scan_error_code',
            field=models.CharField(blank=True, choices=[('virus_detected', 'Virus Detected'), ('timeout', 'Scan Timeout'), ('connection_refused', 'Connection Refused'), ('scanner_error', 'Scanner Error'), ('file_missing', 'File Missing'), ('file_tampered', 'File Tampered'), ('upload_failed', 'ImageKit Upload Failed'), ('unknown_error', 'Unknown Error')], max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='scan_result',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='scanning_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Scan'), ('scanning', 'Scanning'), ('safe', 'Safe'), ('rejected', 'Rejected — Virus Detected'), ('failed', 'Failed — Infrastructure Error')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
