# Generated by Django 6.0.5 on 2026-08-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_grandfather_existing_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='public_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
